use_frameworks!

platform :ios, '8.0'

target 'ComponentMainModule_Example' do
  pod 'ComponentMainModule', :path => '../'

  target 'ComponentMainModule_Tests' do
    inherit! :search_paths

    
  end
end
